services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - CLEAN_RIGHT_ANSWERS=false
    volumes:
      - ./db.sqlite:/app/db.sqlite
      - ./images:/data/images
    # Map any other necessary paths or ports if needed
